import { Router, Request, Response } from 'express';
import { embedText, generateAnswer } from '../lib/gemini';
import { queryVectors } from '../lib/pinecone';
import { buildRAGPrompt } from '../lib/ragPrompt';
import { logger } from '../utils/logger';
import { withRetry } from '../utils/retry';

const router = Router();

router.post('/', async (req: Request, res: Response) => {
  try {
    const { query } = req.body;

    // Validate input
    if (!query || typeof query !== 'string') {
      return res.status(400).json({ error: 'Query is required and must be a string' });
    }

    if (query.trim().length === 0) {
      return res.status(400).json({ error: 'Query cannot be empty' });
    }

    logger.info('Processing query', { query });

    // Generate query embedding
    const queryEmbedding = await withRetry(
      () => embedText(query),
      { maxAttempts: 3, delayMs: 1000 }
    );

    // Query Pinecone for relevant chunks
    const matches = await withRetry(
      () => queryVectors(queryEmbedding, 5),
      { maxAttempts: 3, delayMs: 1000 }
    );

    if (process.env.RAG_DEBUG === 'true') {
      logger.info('RAG Debug - Retrieved chunks', {
        count: matches.length,
        scores: matches.map(m => m.score),
        sources: matches.map(m => m.metadata.source),
      });
    }

    // Handle empty retrieval results gracefully
    if (matches.length === 0) {
      logger.info('No relevant chunks found - using Gemini LLM fallback');
      
      const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${query}\n\nANSWER:`;
      const answer = await withRetry(
        () => generateAnswer(fallbackPrompt),
        { maxAttempts: 3, delayMs: 1000 }
      );

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (no document chunks found)',
          score: 0,
          chunkIndex: -1,
        }],
      });
    }

    // Build context from matches
    const context = matches
      .map((match, idx) => `[${idx + 1}] (Source: ${match.metadata.source})\n${match.metadata.text}`)
      .join('\n\n');

    // Generate RAG prompt
    const prompt = buildRAGPrompt(query, context);

    // Generate answer
    let answer = await withRetry(
      () => generateAnswer(prompt),
      { maxAttempts: 3, delayMs: 1000 }
    );

    // Check if RAG couldn't find answer in documents
    if (answer.includes('Information not found in provided documents')) {
      logger.info('RAG returned "not found" - using Gemini LLM fallback');
      
      const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${query}\n\nANSWER:`;
      answer = await withRetry(
        () => generateAnswer(fallbackPrompt),
        { maxAttempts: 3, delayMs: 1000 }
      );

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (answer not found in document chunks)',
          score: 0,
          chunkIndex: -1,
        }],
      });
    }

    // Format sources
    const sources = matches.map((match) => ({
      source: match.metadata.source,
      score: match.score,
      chunkIndex: match.metadata.chunkIndex,
    }));

    logger.info('Query processed successfully with RAG');

    return res.status(200).json({
      answer,
      sources,
    });
  } catch (error) {
    logger.error('Error processing chat request', error);
    return res.status(500).json({
      error: 'Internal server error',
      message: error instanceof Error ? error.message : 'Unknown error',
    });
  }
});

export default router;
