import 'dotenv/config';
import { embedText, generateAnswer } from '../lib/gemini';
import { queryVectors } from '../lib/pinecone';
import { buildRAGPrompt } from '../lib/ragPrompt';
import { logger } from '../utils/logger';
import { detectLanguage, translateToEnglish, getLanguageName } from '../lib/translator';

interface VercelRequest {
  method: string;
  body: any;
}

interface VercelResponse {
  status: (code: number) => VercelResponse;
  json: (data: any) => void;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  try {
    const { query } = req.body;

    if (!query || typeof query !== 'string') {
      return res.status(400).json({ error: 'Query is required and must be a string' });
    }

    logger.info('Processing query', { query });
    console.log(`\n📝 Original Query: "${query}"`);

    // Step 1: Detect language
    const detectedLanguage = await detectLanguage(query);
    console.log(`🌍 Detected Language: ${detectedLanguage}`);

    let englishQuery = query;
    let translatedQuery = '';

    // Step 2: Translate to English if not already in English
    if (detectedLanguage !== 'en') {
      console.log('🔄 Translating to English...');
      englishQuery = await translateToEnglish(query, detectedLanguage);
      translatedQuery = englishQuery;
      console.log(`📖 English Query: "${englishQuery}"`);
    }

    console.log('-'.repeat(60));

    // Step 3: Embed and query vectors using English text
    const queryEmbedding = await embedText(englishQuery);
    const matches = await queryVectors(queryEmbedding, 10);

    if (matches.length === 0) {
      console.log('⚠ No relevant chunks found - using Gemini LLM fallback');

      const languageName = getLanguageName(detectedLanguage);
      const languageInstruction = detectedLanguage !== 'en' 
        ? `\n\nIMPORTANT: Respond in ${languageName} (language code: ${detectedLanguage}), not English.`
        : '';
      const fallbackPrompt = `Answer the following question concisely and accurately:${languageInstruction}\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
      console.log(`🤖 Gemini will respond directly in: ${languageName} (${detectedLanguage})`);
      let answer = await generateAnswer(fallbackPrompt);

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (no document chunks found)',
        }],
        originalLanguage: detectedLanguage,
        detectedLanguage: detectedLanguage,
        translatedQuery: translatedQuery,
      });
    }

    console.log(`✓ Found ${matches.length} relevant chunks`);

    // Debug: Show all sources
    console.log('Top sources:');
    matches.slice(0, 10).forEach((m, i) => {
      console.log(`  ${i + 1}. ${m.metadata.source} (score: ${m.score.toFixed(4)})`);
    });

    // Check if top match score is too low (< 0.6) - trigger fallback
    const topScore = matches[0]?.score || 0;
    if (topScore < 0.6) {
      console.log(`⚠ Top score too low (${topScore.toFixed(4)} < 0.6) - using Gemini LLM fallback`);

      const languageName = getLanguageName(detectedLanguage);
      const languageInstruction = detectedLanguage !== 'en' 
        ? `\n\nIMPORTANT: Respond in ${languageName} (language code: ${detectedLanguage}), not English.`
        : '';
      const fallbackPrompt = `Answer the following question concisely and accurately:${languageInstruction}\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
      let answer = await generateAnswer(fallbackPrompt);

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (low relevance scores)',
        }],
        originalLanguage: detectedLanguage,
        detectedLanguage: detectedLanguage,
        translatedQuery: translatedQuery,
      });
    }

    const context = matches
      .slice(0, 5)
      .map((match) => match.metadata.text)
      .join('\n\n');

    // Get language name for Gemini instruction
    const languageName = getLanguageName(detectedLanguage);
    const prompt = buildRAGPrompt(englishQuery, context, languageName, detectedLanguage);
    console.log(`🤖 Gemini will respond directly in: ${languageName} (${detectedLanguage})`);
    let answer = await generateAnswer(prompt);

    if (answer.includes("I don't have specific information about that")) {
      console.log('⚠ RAG returned "not found" - using Gemini LLM fallback');

      const languageInstruction = detectedLanguage !== 'en' 
        ? `\n\nIMPORTANT: Respond in ${languageName} (language code: ${detectedLanguage}), not English.`
        : '';
      const fallbackPrompt = `Answer the following question concisely and accurately:${languageInstruction}\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
      answer = await generateAnswer(fallbackPrompt);

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (answer not found in document chunks)',
        }],
        originalLanguage: detectedLanguage,
        detectedLanguage: detectedLanguage,
        translatedQuery: translatedQuery,
      });
    }

    // No translation needed - Gemini responds directly in original language

    const sources = matches.map((match) => ({
      source: `Found in documents: ${match.metadata.source}`,
      score: match.score,
      chunkIndex: match.metadata.chunkIndex,
    }));

    return res.status(200).json({
      answer,
      sources,
      originalLanguage: detectedLanguage,
      detectedLanguage: detectedLanguage,
      translatedQuery: translatedQuery,
    });
  } catch (error) {
    logger.error('Error processing chat request', error);
    return res.status(500).json({
      error: 'Internal server error',
      message: error instanceof Error ? error.message : 'Unknown error',
    });
  }
}
