import 'dotenv/config';
import { embedText, generateAnswer } from '../lib/gemini';
import { queryVectors } from '../lib/pinecone';
import { buildRAGPrompt } from '../lib/ragPrompt';
import { logger } from '../utils/logger';
import { detectLanguage, translateToEnglish } from '../lib/translator';
import { validateQueryTopic, getRejectionMessage } from '../lib/topicValidator';

interface VercelRequest {
  method: string;
  body: any;
}

interface VercelResponse {
  status: (code: number) => VercelResponse;
  json: (data: any) => void;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  try {
    const { query } = req.body;

    if (!query || typeof query !== 'string') {
      return res.status(400).json({ error: 'Query is required and must be a string' });
    }

    logger.info('Processing query', { query });
    console.log(`\n📝 Original Query: "${query}"`);

    // Step 1: Detect language
    const detectedLanguage = await detectLanguage(query);
    console.log(`🌍 Detected Language: ${detectedLanguage}`);

    let englishQuery = query;
    let translatedQuery = '';

    // Step 2: Translate to English if not already in English
    if (detectedLanguage !== 'en') {
      console.log('🔄 Translating to English...');
      englishQuery = await translateToEnglish(query, detectedLanguage);
      translatedQuery = englishQuery;
      console.log(`📖 English Query: "${englishQuery}"`);
    }

    // Step 2.5: Validate if query is related to allowed topics
    console.log('🔍 Validating query topic...');
    const topicValidation = await validateQueryTopic(englishQuery);
    
    if (!topicValidation.isValid) {
      console.log('❌ Query topic validation failed - not farming/agriculture related');
      
      // Get pre-translated rejection message - NO API CALL NEEDED
      const rejectionMessage = getRejectionMessage(detectedLanguage);
      
      return res.status(200).json({
        answer: rejectionMessage,
        sources: [],
        originalLanguage: detectedLanguage,
        detectedLanguage: detectedLanguage,
        translatedQuery: translatedQuery,
        topicValidation: false,
      });
    }
    
    console.log('✓ Query topic validation passed');

    console.log('-'.repeat(60));

    // Step 3: Embed and query vectors using English text
    const queryEmbedding = await embedText(englishQuery);
    const matches = await queryVectors(queryEmbedding, 10);

    if (matches.length === 0) {
      console.log('⚠ No relevant chunks found - using Gemini LLM fallback');

      // Generate answer directly in target language
      const fallbackPrompt = detectedLanguage !== 'en'
        ? `You are a farming and agricultural advisor. Answer the following question concisely and accurately in ${detectedLanguage} language (the same language as the original question "${query}"). Only answer if the question is related to farming, agriculture, environment, weather, banking/loans, government schemes, or farming news.\n\nQUESTION: ${englishQuery}\n\nANSWER in ${detectedLanguage}:`
        : `You are a farming and agricultural advisor. Answer the following question concisely and accurately. Only answer if the question is related to farming, agriculture, environment, weather, banking/loans, government schemes, or farming news.\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
      const answer = await generateAnswer(fallbackPrompt);

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (no document chunks found)',
        }],
        originalLanguage: detectedLanguage,
        detectedLanguage: detectedLanguage,
        translatedQuery: translatedQuery,
      });
    }

    console.log(`✓ Found ${matches.length} relevant chunks`);

    // Debug: Show all sources
    console.log('Top sources:');
    matches.slice(0, 10).forEach((m, i) => {
      console.log(`  ${i + 1}. ${m.metadata.source} (score: ${m.score.toFixed(4)})`);
    });

    // Check if top match score is too low (< 0.6) - trigger fallback
    const topScore = matches[0]?.score || 0;
    if (topScore < 0.6) {
      console.log(`⚠ Top score too low (${topScore.toFixed(4)} < 0.6) - using Gemini LLM fallback`);

      // Generate answer directly in target language
      const fallbackPrompt = detectedLanguage !== 'en'
        ? `You are a farming and agricultural advisor. Answer the following question concisely and accurately in ${detectedLanguage} language (the same language as the original question "${query}"). Only answer if the question is related to farming, agriculture, environment, weather, banking/loans, government schemes, or farming news.\n\nQUESTION: ${englishQuery}\n\nANSWER in ${detectedLanguage}:`
        : `You are a farming and agricultural advisor. Answer the following question concisely and accurately. Only answer if the question is related to farming, agriculture, environment, weather, banking/loans, government schemes, or farming news.\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
      const answer = await generateAnswer(fallbackPrompt);

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (low relevance scores)',
        }],
        originalLanguage: detectedLanguage,
        detectedLanguage: detectedLanguage,
        translatedQuery: translatedQuery,
      });
    }

    const context = matches
      .slice(0, 5)
      .map((match) => match.metadata.text)
      .join('\n\n');

    // Generate answer directly in target language using buildRAGPrompt with language parameters
    const languageNames: Record<string, string> = {
      'en': 'English',
      'hi': 'Hindi',
      'bn': 'Bengali',
      'es': 'Spanish',
      'fr': 'French',
      'de': 'German',
      'zh': 'Chinese',
      'ar': 'Arabic',
      'pt': 'Portuguese',
      'ru': 'Russian',
    };
    
    const targetLanguageName = languageNames[detectedLanguage] || detectedLanguage;
    const prompt = buildRAGPrompt(englishQuery, context, targetLanguageName, detectedLanguage);
    let answer = await generateAnswer(prompt);

    if (answer.includes("I don't have specific information about that")) {
      console.log('⚠ RAG returned "not found" - using Gemini LLM fallback');

      // Generate answer directly in target language
      const fallbackPrompt = detectedLanguage !== 'en'
        ? `You are a farming and agricultural advisor. Answer the following question concisely and accurately in ${detectedLanguage} language (the same language as the original question "${query}"). Only answer if the question is related to farming, agriculture, environment, weather, banking/loans, government schemes, or farming news.\n\nQUESTION: ${englishQuery}\n\nANSWER in ${detectedLanguage}:`
        : `You are a farming and agricultural advisor. Answer the following question concisely and accurately. Only answer if the question is related to farming, agriculture, environment, weather, banking/loans, government schemes, or farming news.\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
      answer = await generateAnswer(fallbackPrompt);

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (answer not found in document chunks)',
        }],
        originalLanguage: detectedLanguage,
        detectedLanguage: detectedLanguage,
        translatedQuery: translatedQuery,
      });
    }

    // No translation needed - Gemini responds directly in original language

    const sources = matches.map((match) => ({
      source: `Found in documents: ${match.metadata.source}`,
      score: match.score,
      chunkIndex: match.metadata.chunkIndex,
    }));

    return res.status(200).json({
      answer,
      sources,
      originalLanguage: detectedLanguage,
      detectedLanguage: detectedLanguage,
      translatedQuery: translatedQuery,
    });
  } catch (error) {
    logger.error('Error processing chat request', error);
    return res.status(500).json({
      error: 'Internal server error',
      message: error instanceof Error ? error.message : 'Unknown error',
    });
  }
}
