import 'dotenv/config';
import { embedText, generateAnswer } from '../src/lib/gemini';
import { queryVectors } from '../src/lib/pinecone';
import { buildRAGPrompt } from '../src/lib/ragPrompt';
import { logger } from '../src/utils/logger';
import { detectLanguage, translateToEnglish, translateFromEnglish } from '../src/lib/translator';

interface ChatResponse {
  answer: string;
  sources: Array<{
    source: string;
    score?: number;
    chunkIndex?: number;
  }>;
  originalLanguage?: string;
  detectedLanguage?: string;
  translatedQuery?: string;
}

async function simulateChatRequest(query: string): Promise<ChatResponse> {
  console.log(`\n📝 Original Query: "${query}"`);
  
  // Step 1: Detect language
  const detectedLanguage = await detectLanguage(query);
  console.log(`🌍 Detected Language: ${detectedLanguage}`);
  
  let englishQuery = query;
  let translatedQuery = '';
  
  // Step 2: Translate to English if not already in English
  if (detectedLanguage !== 'en') {
    console.log('🔄 Translating to English...');
    englishQuery = await translateToEnglish(query, detectedLanguage);
    translatedQuery = englishQuery;
    console.log(`📖 English Query: "${englishQuery}"`);
  }
  
  console.log('-'.repeat(60));

  // Step 3: Embed and query vectors using English text
  const queryEmbedding = await embedText(englishQuery);
  const matches = await queryVectors(queryEmbedding, 10);

  if (matches.length === 0) {
    console.log('⚠ No relevant chunks found - using Gemini LLM fallback');
    
    const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
    let answer = await generateAnswer(fallbackPrompt);
    
    // Step 4: Translate answer back if needed
    if (detectedLanguage !== 'en') {
      console.log('🔄 Translating answer back to original language...');
      answer = await translateFromEnglish(answer, detectedLanguage);
    }
    
    return {
      answer,
      sources: [{
        source: 'Generated by Gemini (no document chunks found)',
      }],
      originalLanguage: detectedLanguage,
      detectedLanguage: detectedLanguage,
      translatedQuery: translatedQuery,
    };
  }

  console.log(`✓ Found ${matches.length} relevant chunks`);
  
  // Debug: Show all sources
  console.log('Top sources:');
  matches.slice(0, 10).forEach((m, i) => {
    console.log(`  ${i + 1}. ${m.metadata.source} (score: ${m.score.toFixed(4)})`);
  });

  const context = matches
    .slice(0, 5)
    .map((match, idx) => `[${idx + 1}] (Source: ${match.metadata.source})\n${match.metadata.text}`)
    .join('\n\n');

  const prompt = buildRAGPrompt(englishQuery, context);
  let answer = await generateAnswer(prompt);

  if (answer.includes('Information not found in provided documents')) {
    console.log('⚠ RAG returned "not found" - using Gemini LLM fallback');
    
    const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
    answer = await generateAnswer(fallbackPrompt);
    
    // Translate answer back if needed
    if (detectedLanguage !== 'en') {
      console.log('🔄 Translating answer back to original language...');
      answer = await translateFromEnglish(answer, detectedLanguage);
    }
    
    return {
      answer,
      sources: [{
        source: 'Generated by Gemini (answer not found in document chunks)',
      }],
      originalLanguage: detectedLanguage,
      detectedLanguage: detectedLanguage,
      translatedQuery: translatedQuery,
    };
  }

  // Step 4: Translate answer back to original language if needed
  if (detectedLanguage !== 'en') {
    console.log('🔄 Translating answer back to original language...');
    answer = await translateFromEnglish(answer, detectedLanguage);
  }

  const sources = matches.map((match) => ({
    source: `Found in documents: ${match.metadata.source}`,
    score: match.score,
    chunkIndex: match.metadata.chunkIndex,
  }));

  return { 
    answer, 
    sources,
    originalLanguage: detectedLanguage,
    detectedLanguage: detectedLanguage,
    translatedQuery: translatedQuery,
  };
}

async function testChat() {
  try {
    console.log('='.repeat(60));
    console.log('CHAT API TEST WITH TRANSLATION');
    console.log('='.repeat(60));

    const queries = [
      // English
      // Bengali
      'আলুতে লেট ব্লাইট রোগ কী এবং এটি কীভাবে প্রতিরোধ করা যায়?',
      // Spanish
    ];


    for (const query of queries) {
      const response = await simulateChatRequest(query);

      console.log('\n✓ Final Answer:');
      console.log(response.answer);
      
      if (response.detectedLanguage && response.detectedLanguage !== 'en') {
        console.log(`\n📊 Translation Info:`);
        console.log(`   Original Language: ${response.detectedLanguage.toUpperCase()}`);
        console.log(`   Query Translated to English: ${response.translatedQuery}`);
      }

      console.log('\n📚 Sources:');
      if (response.sources.length === 0) {
        console.log('  (none)');
      } else {
        response.sources.forEach((src, idx) => {
          const scoreInfo = src.score !== undefined ? ` (score: ${src.score.toFixed(4)}, chunk: ${src.chunkIndex})` : '';
          console.log(`  [${idx + 1}] ${src.source}${scoreInfo}`);
        });
      }

      console.log('\n' + '='.repeat(60));
      
      await new Promise(resolve => setTimeout(resolve, 1000));
    }

    console.log('\n✅ ALL TESTS COMPLETED');

  } catch (error) {
    logger.error('Chat test failed', error);
    console.error('❌ Test failed:', error);
    process.exit(1);
  }
}

testChat();
