"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("dotenv/config");
const gemini_1 = require("../src/lib/gemini");
const pinecone_1 = require("../src/lib/pinecone");
const ragPrompt_1 = require("../src/lib/ragPrompt");
const logger_1 = require("../src/utils/logger");
async function simulateChatRequest(query) {
    console.log(`\n📝 Query: "${query}"`);
    console.log('-'.repeat(60));
    const queryEmbedding = await (0, gemini_1.embedText)(query);
    const matches = await (0, pinecone_1.queryVectors)(queryEmbedding, 5);
    if (matches.length === 0) {
        console.log('⚠ No relevant chunks found - using Gemini LLM fallback');
        const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${query}\n\nANSWER:`;
        const answer = await (0, gemini_1.generateAnswer)(fallbackPrompt);
        return {
            answer,
            sources: [{
                    source: 'Generated by Gemini (no document chunks found)',
                }],
        };
    }
    console.log(`✓ Found ${matches.length} relevant chunks`);
    if (process.env.RAG_DEBUG === 'true') {
        console.log('Chunk scores:', matches.map(m => m.score.toFixed(4)).join(', '));
    }
    const context = matches
        .map((match, idx) => `[${idx + 1}] (Source: ${match.metadata.source})\n${match.metadata.text}`)
        .join('\n\n');
    const prompt = (0, ragPrompt_1.buildRAGPrompt)(query, context);
    let answer = await (0, gemini_1.generateAnswer)(prompt);
    if (answer.includes('Information not found in provided documents')) {
        console.log('⚠ RAG returned "not found" - using Gemini LLM fallback');
        const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${query}\n\nANSWER:`;
        answer = await (0, gemini_1.generateAnswer)(fallbackPrompt);
        return {
            answer,
            sources: [{
                    source: 'Generated by Gemini (answer not found in document chunks)',
                }],
        };
    }
    const sources = matches.map((match) => ({
        source: `Found in documents: ${match.metadata.source}`,
        score: match.score,
        chunkIndex: match.metadata.chunkIndex,
    }));
    return { answer, sources };
}
async function testChat() {
    try {
        console.log('='.repeat(60));
        console.log('CHAT API TEST');
        console.log('='.repeat(60));
        const queries = [
            // Core agriculture concepts
            'What is soil fertility and how can it be improved?',
            'What is organic farming?',
            'Explain sustainable agriculture practices.',
            'What is crop rotation and why is it important?',
            'What are the advantages of organic farming?',
            'What is soil fertility and how can it be improved?',
            // Crop & soil management
            'How does crop rotation improve soil health?',
            'What are common methods of soil conservation?',
            'What is green manure in agriculture?',
            'Explain the importance of irrigation in farming.',
            'What is mixed cropping?',
            // Environmental & climate
            'How does agriculture impact the environment?',
            'What is sustainable water management in agriculture?',
            'How can farmers reduce soil erosion?',
        ];
        for (const query of queries) {
            const response = await simulateChatRequest(query);
            console.log('\n✓ Answer:');
            console.log(response.answer);
            console.log('\n📚 Sources:');
            if (response.sources.length === 0) {
                console.log('  (none)');
            }
            else {
                response.sources.forEach((src, idx) => {
                    const scoreInfo = src.score !== undefined ? ` (score: ${src.score.toFixed(4)}, chunk: ${src.chunkIndex})` : '';
                    console.log(`  [${idx + 1}] ${src.source}${scoreInfo}`);
                });
            }
            console.log('\n' + '='.repeat(60));
            await new Promise(resolve => setTimeout(resolve, 1000));
        }
        console.log('\n✅ ALL TESTS COMPLETED');
    }
    catch (error) {
        logger_1.logger.error('Chat test failed', error);
        console.error('❌ Test failed:', error);
        process.exit(1);
    }
}
testChat();
