import 'dotenv/config';
import { embedText, generateAnswer } from '../src/lib/gemini';
import { queryVectors } from '../src/lib/pinecone';
import { buildRAGPrompt } from '../src/lib/ragPrompt';
import { logger } from '../src/utils/logger';
import { detectLanguage, translateToEnglish, translateFromEnglish } from '../src/lib/translator';

interface ChatResponse {
  answer: string;
  sources: Array<{
    source: string;
    score?: number;
    chunkIndex?: number;
  }>;
  originalLanguage?: string;
  detectedLanguage?: string;
  translatedQuery?: string;
}

async function simulateChatRequest(query: string): Promise<ChatResponse> {
  console.log(`\n📝 Original Query: "${query}"`);
  
  // Step 1: Detect language
  const detectedLanguage = await detectLanguage(query);
  console.log(`🌍 Detected Language: ${detectedLanguage}`);
  
  let englishQuery = query;
  let translatedQuery = '';
  
  // Step 2: Translate to English if not already in English
  if (detectedLanguage !== 'en') {
    console.log('🔄 Translating to English...');
    englishQuery = await translateToEnglish(query, detectedLanguage);
    translatedQuery = englishQuery;
    console.log(`📖 English Query: "${englishQuery}"`);
  }
  
  console.log('-'.repeat(60));

  // Step 3: Embed and query vectors using English text
  const queryEmbedding = await embedText(englishQuery);
  const matches = await queryVectors(queryEmbedding, 10);

  if (matches.length === 0) {
    console.log('⚠ No relevant chunks found - using Gemini LLM fallback');
    
    // Generate answer directly in target language
    const fallbackPrompt = detectedLanguage !== 'en'
      ? `Answer the following question concisely and accurately in ${detectedLanguage} language (the same language as the original question "${query}"):\n\nQUESTION: ${englishQuery}\n\nANSWER in ${detectedLanguage}:`
      : `Answer the following question concisely and accurately:\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
    const answer = await generateAnswer(fallbackPrompt);
    
    return {
      answer,
      sources: [{
        source: 'Generated by Gemini (no document chunks found)',
      }],
      originalLanguage: detectedLanguage,
      detectedLanguage: detectedLanguage,
      translatedQuery: translatedQuery,
    };
  }

  console.log(`✓ Found ${matches.length} relevant chunks`);
  
  // Debug: Show all sources
  console.log('Top sources:');
  matches.slice(0, 10).forEach((m, i) => {
    console.log(`  ${i + 1}. ${m.metadata.source} (score: ${m.score.toFixed(4)})`);
  });

  // Check if top match score is too low (< 0.6) - trigger fallback
  const topScore = matches[0]?.score || 0;
  if (topScore < 0.6) {
    console.log(`⚠ Top score too low (${topScore.toFixed(4)} < 0.6) - using Gemini LLM fallback`);
    
    // Generate answer directly in target language
    const fallbackPrompt = detectedLanguage !== 'en'
      ? `Answer the following question concisely and accurately in ${detectedLanguage} language (the same language as the original question "${query}"):\n\nQUESTION: ${englishQuery}\n\nANSWER in ${detectedLanguage}:`
      : `Answer the following question concisely and accurately:\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
    const answer = await generateAnswer(fallbackPrompt);
    
    return {
      answer,
      sources: [{
        source: 'Generated by Gemini (low relevance scores)',
      }],
      originalLanguage: detectedLanguage,
      detectedLanguage: detectedLanguage,
      translatedQuery: translatedQuery,
    };
  }

  const context = matches
    .slice(0, 5)
    .map((match) => match.metadata.text)
    .join('\n\n');

  // Generate answer directly in target language using buildRAGPrompt with language parameters
  const languageNames: Record<string, string> = {
    'en': 'English',
    'hi': 'Hindi',
    'bn': 'Bengali',
    'es': 'Spanish',
    'fr': 'French',
    'de': 'German',
    'zh': 'Chinese',
    'ar': 'Arabic',
    'pt': 'Portuguese',
    'ru': 'Russian',
  };
  
  const targetLanguageName = languageNames[detectedLanguage] || detectedLanguage;
  const prompt = buildRAGPrompt(englishQuery, context, targetLanguageName, detectedLanguage);
  let answer = await generateAnswer(prompt);

  if (answer.includes("I don't have specific information about that")) {
    console.log('⚠ RAG returned "not found" - using Gemini LLM fallback');
    
    // Generate answer directly in target language
    const fallbackPrompt = detectedLanguage !== 'en'
      ? `Answer the following question concisely and accurately in ${detectedLanguage} language (the same language as the original question "${query}"):\n\nQUESTION: ${englishQuery}\n\nANSWER in ${detectedLanguage}:`
      : `Answer the following question concisely and accurately:\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
    answer = await generateAnswer(fallbackPrompt);
    
    return {
      answer,
      sources: [{
        source: 'Generated by Gemini (answer not found in document chunks)',
      }],
      originalLanguage: detectedLanguage,
      detectedLanguage: detectedLanguage,
      translatedQuery: translatedQuery,
    };
  }

  const sources = matches.map((match) => ({
    source: `Found in documents: ${match.metadata.source}`,
    score: match.score,
    chunkIndex: match.metadata.chunkIndex,
  }));

  return { 
    answer, 
    sources,
    originalLanguage: detectedLanguage,
    detectedLanguage: detectedLanguage,
    translatedQuery: translatedQuery,
  };
}

async function testChat() {
  try {
    console.log('='.repeat(60));
    console.log('CHAT API TEST WITH TRANSLATION');
    console.log('='.repeat(60));

    const queries = [
      // English
      // Bengali
      'chawal se kya kya banta hai',
      // Spanish
    ];


    for (const query of queries) {
      const response = await simulateChatRequest(query);

      console.log('\n✓ Final Answer:');
      console.log(response.answer);
      
      if (response.detectedLanguage && response.detectedLanguage !== 'en') {
        console.log(`\n📊 Translation Info:`);
        console.log(`   Original Language: ${response.detectedLanguage.toUpperCase()}`);
        console.log(`   Query Translated to English: ${response.translatedQuery}`);
      }

      console.log('\n📚 Sources:');
      if (response.sources.length === 0) {
        console.log('  (none)');
      } else {
        response.sources.forEach((src, idx) => {
          const scoreInfo = src.score !== undefined ? ` (score: ${src.score.toFixed(4)}, chunk: ${src.chunkIndex})` : '';
          console.log(`  [${idx + 1}] ${src.source}${scoreInfo}`);
        });
      }

      console.log('\n' + '='.repeat(60));
      
      await new Promise(resolve => setTimeout(resolve, 1000));
    }

    console.log('\n✅ ALL TESTS COMPLETED');

  } catch (error) {
    logger.error('Chat test failed', error);
    console.error('❌ Test failed:', error);
    process.exit(1);
  }
}

testChat();
