import 'dotenv/config';
import { embedText, generateAnswer } from '../src/lib/gemini';
import { queryVectors } from '../src/lib/pinecone';
import { buildRAGPrompt } from '../src/lib/ragPrompt';
import { logger } from '../src/utils/logger';

interface ChatResponse {
  answer: string;
  sources: Array<{
    source: string;
    score?: number;
    chunkIndex?: number;
  }>;
}

async function simulateChatRequest(query: string): Promise<ChatResponse> {
  console.log(`\n📝 Query: "${query}"`);
  console.log('-'.repeat(60));

  const queryEmbedding = await embedText(query);
  const matches = await queryVectors(queryEmbedding, 10); // Increased to see more results

  if (matches.length === 0) {
    console.log('⚠ No relevant chunks found - using Gemini LLM fallback');
    
    const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${query}\n\nANSWER:`;
    const answer = await generateAnswer(fallbackPrompt);
    
    return {
      answer,
      sources: [{
        source: 'Generated by Gemini (no document chunks found)',
      }],
    };
  }

  console.log(`✓ Found ${matches.length} relevant chunks`);
  
  // Debug: Show all sources
  console.log('Top sources:');
  matches.slice(0, 10).forEach((m, i) => {
    console.log(`  ${i + 1}. ${m.metadata.source} (score: ${m.score.toFixed(4)})`);
  });

  const context = matches
    .slice(0, 5)
    .map((match, idx) => `[${idx + 1}] (Source: ${match.metadata.source})\n${match.metadata.text}`)
    .join('\n\n');

  const prompt = buildRAGPrompt(query, context);
  let answer = await generateAnswer(prompt);

  if (answer.includes('Information not found in provided documents')) {
    console.log('⚠ RAG returned "not found" - using Gemini LLM fallback');
    
    const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${query}\n\nANSWER:`;
    answer = await generateAnswer(fallbackPrompt);
    
    return {
      answer,
      sources: [{
        source: 'Generated by Gemini (answer not found in document chunks)',
      }],
    };
  }

  const sources = matches.map((match) => ({
    source: `Found in documents: ${match.metadata.source}`,
    score: match.score,
    chunkIndex: match.metadata.chunkIndex,
  }));

  return { answer, sources };
}

async function testChat() {
  try {
    console.log('='.repeat(60));
    console.log('CHAT API TEST');
    console.log('='.repeat(60));

    const queries = [
  'what is crop rotation',
  'what are the different methods of irrigation?',
  'Which crop is the major source of food in africa?',
  'what is the major cassava disease?',
];


    for (const query of queries) {
      const response = await simulateChatRequest(query);

      console.log('\n✓ Answer:');
      console.log(response.answer);

      console.log('\n📚 Sources:');
      if (response.sources.length === 0) {
        console.log('  (none)');
      } else {
        response.sources.forEach((src, idx) => {
          const scoreInfo = src.score !== undefined ? ` (score: ${src.score.toFixed(4)}, chunk: ${src.chunkIndex})` : '';
          console.log(`  [${idx + 1}] ${src.source}${scoreInfo}`);
        });
      }

      console.log('\n' + '='.repeat(60));
      
      await new Promise(resolve => setTimeout(resolve, 1000));
    }

    console.log('\n✅ ALL TESTS COMPLETED');

  } catch (error) {
    logger.error('Chat test failed', error);
    console.error('❌ Test failed:', error);
    process.exit(1);
  }
}

testChat();
