import { embedText } from '../src/lib/gemini';
import { generateAnswer } from '../src/lib/gemini';
import { queryVectors } from '../src/lib/pinecone';
import { buildRAGPrompt } from '../src/lib/ragPrompt';
import { logger } from '../src/utils/logger';
import { withRetry } from '../src/utils/retry';
import { detectLanguage, translateText, translateAnswer } from '../src/lib/translator';

interface VercelRequest {
  method: string;
  body: any;
}

interface VercelResponse {
  status: (code: number) => VercelResponse;
  json: (data: any) => void;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { query } = req.body;

    if (!query || typeof query !== 'string') {
      return res.status(400).json({ error: 'Query is required and must be a string' });
    }

    logger.info('Processing query', { query });

    // Detect the original language of the query
    const originalLanguage = await withRetry(
      () => detectLanguage(query),
      { maxAttempts: 3, delayMs: 1000 }
    );

    logger.info('Detected language', { originalLanguage, query: query.substring(0, 50) });

    // Translate query to English if it's not already in English
    let englishQuery = query;
    if (originalLanguage !== 'en') {
      englishQuery = await withRetry(
        () => translateText(query, 'en'),
        { maxAttempts: 3, delayMs: 1000 }
      );
      logger.info('Translated query to English', { 
        originalLanguage,
        englishQuery: englishQuery.substring(0, 50)
      });
    }

    // Use English query for embedding and RAG
    const queryEmbedding = await withRetry(
      () => embedText(englishQuery),
      { maxAttempts: 3, delayMs: 1000 }
    );

    const matches = await withRetry(
      () => queryVectors(queryEmbedding, 3),
      { maxAttempts: 3, delayMs: 1000 }
    );

    if (process.env.RAG_DEBUG === 'true') {
      logger.info('RAG Debug - Retrieved chunks', {
        count: matches.length,
        scores: matches.map((m: any) => m.score),
        sources: matches.map((m: any) => m.metadata.source),
      });
    }

    if (matches.length === 0) {
      logger.info('No relevant chunks found - using Gemini LLM fallback');
      
      const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
      let answer = await withRetry(
        () => generateAnswer(fallbackPrompt),
        { maxAttempts: 3, delayMs: 1000 }
      );

      // Translate answer back to original language if needed
      if (originalLanguage !== 'en') {
        answer = await withRetry(
          () => translateAnswer(answer, originalLanguage),
          { maxAttempts: 3, delayMs: 1000 }
        );
      }

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (no document chunks found)',
        }],
      });
    }

    const context = matches
      .map((match: any, idx: number) => `[${idx + 1}] (Source: ${match.metadata.source})\n${match.metadata.text}`)
      .join('\n\n');

    const prompt = buildRAGPrompt(englishQuery, context);

    let answer = await withRetry(
      () => generateAnswer(prompt),
      { maxAttempts: 3, delayMs: 1000 }
    );

    // Check if RAG answer is unhelpful or indicates no information
    const unhelpfulPatterns = [
      'Information not found in provided documents',
      'I don\'t have information',
      'I don\'t have any information',
      'not available in the documents',
      'cannot answer',
      'no information available',
      'unable to answer',
      'not mentioned in the context',
      'not provided in the documents',
      'I cannot find',
    ];

    const isUnhelpfulAnswer = unhelpfulPatterns.some(pattern => 
      answer.toLowerCase().includes(pattern.toLowerCase())
    );

    if (isUnhelpfulAnswer) {
      logger.info('RAG returned unhelpful answer - using Gemini LLM fallback');
      
      const fallbackPrompt = `Answer the following question concisely and accurately in 60-100 words:\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
      answer = await withRetry(
        () => generateAnswer(fallbackPrompt),
        { maxAttempts: 3, delayMs: 1000 }
      );

      // Translate answer back to original language if needed
      if (originalLanguage !== 'en') {
        answer = await withRetry(
          () => translateAnswer(answer, originalLanguage),
          { maxAttempts: 3, delayMs: 1000 }
        );
      }

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (answer not found in document chunks)',
        }],
      });
    }

    const sources = matches.map((match: any) => ({
      source: `Found in documents: ${match.metadata.source}`,
      score: match.score,
      chunkIndex: match.metadata.chunkIndex,
    }));

    // Translate answer back to original language if needed
    if (originalLanguage !== 'en') {
      answer = await withRetry(
        () => translateAnswer(answer, originalLanguage),
        { maxAttempts: 3, delayMs: 1000 }
      );
    }

    logger.info('Query processed successfully with RAG');

    return res.status(200).json({
      answer,
      sources,
    });
  } catch (error) {
    logger.error('Error processing chat request', error);
    return res.status(500).json({
      error: 'Internal server error',
      message: error instanceof Error ? error.message : 'Unknown error',
    });
  }
}
