import 'dotenv/config';
import { embedText, generateAnswer } from '../src/lib/gemini';
import { queryVectors } from '../src/lib/pinecone';
import { buildRAGPrompt } from '../src/lib/ragPrompt';
import { logger } from '../src/utils/logger';
import { withRetry } from '../src/utils/retry';
import { detectLanguage, translateToEnglish, translateFromEnglish } from '../src/lib/translator';

interface VercelRequest {
  method: string;
  body: any;
}

interface VercelResponse {
  status: (code: number) => VercelResponse;
  json: (data: any) => void;
}

interface ChatResponse {
  answer: string;
  sources: Array<{
    source: string;
    score?: number;
    chunkIndex?: number;
  }>;
  originalLanguage?: string;
  detectedLanguage?: string;
  translatedQuery?: string;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { query } = req.body;

    if (!query || typeof query !== 'string') {
      return res.status(400).json({ error: 'Query is required and must be a string' });
    }

    logger.info('Processing query', { query });
    console.log(`\n📝 Original Query: "${query}"`);

    // Step 1: Detect the original language of the query
    const detectedLanguage = await withRetry(
      () => detectLanguage(query),
      { maxAttempts: 3, delayMs: 1000 }
    );

    logger.info('Detected language', { detectedLanguage, query: query.substring(0, 50) });
    console.log(`🌍 Detected Language: ${detectedLanguage}`);

    // Step 2: Translate query to English if it's not already in English
    let englishQuery = query;
    let translatedQuery = '';
    if (detectedLanguage !== 'en') {
      console.log('🔄 Translating to English...');
      englishQuery = await withRetry(
        () => translateToEnglish(query, detectedLanguage),
        { maxAttempts: 3, delayMs: 1000 }
      );
      translatedQuery = englishQuery;
      logger.info('Translated query to English', { 
        detectedLanguage,
        englishQuery: englishQuery.substring(0, 50)
      });
      console.log(`📖 English Query: "${englishQuery}"`);
    }

    console.log('-'.repeat(60));

    // Step 3: Use English query for embedding and RAG
    const queryEmbedding = await withRetry(
      () => embedText(englishQuery),
      { maxAttempts: 3, delayMs: 1000 }
    );

    const matches = await withRetry(
      () => queryVectors(queryEmbedding, 10),
      { maxAttempts: 3, delayMs: 1000 }
    );

    if (process.env.RAG_DEBUG === 'true') {
      logger.info('RAG Debug - Retrieved chunks', {
        count: matches.length,
        scores: matches.map((m: any) => m.score),
        sources: matches.map((m: any) => m.metadata.source),
      });
    }

    if (matches.length === 0) {
      console.log('⚠ No relevant chunks found - using Gemini LLM fallback');
      logger.info('No relevant chunks found - using Gemini LLM fallback');
      
      const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
      let answer = await withRetry(
        () => generateAnswer(fallbackPrompt),
        { maxAttempts: 3, delayMs: 1000 }
      );

      // Step 4: Translate answer back to original language if needed
      if (detectedLanguage !== 'en') {
        console.log('🔄 Translating answer back to original language...');
        answer = await withRetry(
          () => translateFromEnglish(answer, detectedLanguage),
          { maxAttempts: 3, delayMs: 1000 }
        );
      }

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (no document chunks found)',
        }],
        originalLanguage: detectedLanguage,
        detectedLanguage: detectedLanguage,
        translatedQuery: translatedQuery,
      });
    }

    console.log(`✓ Found ${matches.length} relevant chunks`);
    
    // Debug: Show all sources
    console.log('Top sources:');
    matches.slice(0, 10).forEach((m, i) => {
      console.log(`  ${i + 1}. ${m.metadata.source} (score: ${m.score.toFixed(4)})`);
    });

    const context = matches
      .slice(0, 5)
      .map((match: any, idx: number) => `[${idx + 1}] (Source: ${match.metadata.source})\n${match.metadata.text}`)
      .join('\n\n');

    const prompt = buildRAGPrompt(englishQuery, context);

    let answer = await withRetry(
      () => generateAnswer(prompt),
      { maxAttempts: 3, delayMs: 1000 }
    );

    // Check if RAG answer indicates no information found
    if (answer.includes('Information not found in provided documents')) {
      console.log('⚠ RAG returned "not found" - using Gemini LLM fallback');
      logger.info('RAG returned unhelpful answer - using Gemini LLM fallback');
      
      const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${englishQuery}\n\nANSWER:`;
      answer = await withRetry(
        () => generateAnswer(fallbackPrompt),
        { maxAttempts: 3, delayMs: 1000 }
      );

      // Translate answer back to original language if needed
      if (detectedLanguage !== 'en') {
        console.log('🔄 Translating answer back to original language...');
        answer = await withRetry(
          () => translateFromEnglish(answer, detectedLanguage),
          { maxAttempts: 3, delayMs: 1000 }
        );
      }

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (answer not found in document chunks)',
        }],
        originalLanguage: detectedLanguage,
        detectedLanguage: detectedLanguage,
        translatedQuery: translatedQuery,
      });
    }

    // Step 4: Translate answer back to original language if needed
    if (detectedLanguage !== 'en') {
      console.log('🔄 Translating answer back to original language...');
      answer = await withRetry(
        () => translateFromEnglish(answer, detectedLanguage),
        { maxAttempts: 3, delayMs: 1000 }
      );
    }

    logger.info('Query processed successfully with RAG');

    const sources = matches.map((match: any) => ({
      source: `Found in documents: ${match.metadata.source}`,
      score: match.score,
      chunkIndex: match.metadata.chunkIndex,
    }));

    return res.status(200).json({
      answer,
      sources,
      originalLanguage: detectedLanguage,
      detectedLanguage: detectedLanguage,
      translatedQuery: translatedQuery,
    });
  } catch (error) {
    logger.error('Error processing chat request', error);
    return res.status(500).json({
      error: 'Internal server error',
      message: error instanceof Error ? error.message : 'Unknown error',
    });
  }
}
