import type { VercelRequest, VercelResponse } from '@vercel/node';
import { embedText } from '../lib/gemini';
import { generateAnswer } from '../lib/gemini';
import { queryVectors } from '../lib/pinecone';
import { buildRAGPrompt } from '../lib/ragPrompt';
import { logger } from '../utils/logger';
import { withRetry } from '../utils/retry';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { query } = req.body;

    if (!query || typeof query !== 'string') {
      return res.status(400).json({ error: 'Query is required and must be a string' });
    }

    logger.info('Processing query', { query });

    const queryEmbedding = await withRetry(
      () => embedText(query),
      { maxAttempts: 3, delayMs: 1000 }
    );

    const matches = await withRetry(
      () => queryVectors(queryEmbedding, 5),
      { maxAttempts: 3, delayMs: 1000 }
    );

    if (process.env.RAG_DEBUG === 'true') {
      logger.info('RAG Debug - Retrieved chunks', {
        count: matches.length,
        scores: matches.map(m => m.score),
        sources: matches.map(m => m.metadata.source),
      });
    }

    if (matches.length === 0) {
      logger.info('No relevant chunks found - using Gemini LLM fallback');
      
      const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${query}\n\nANSWER:`;
      const answer = await withRetry(
        () => generateAnswer(fallbackPrompt),
        { maxAttempts: 3, delayMs: 1000 }
      );

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (no document chunks found)',
        }],
      });
    }

    const context = matches
      .map((match, idx) => `[${idx + 1}] (Source: ${match.metadata.source})\n${match.metadata.text}`)
      .join('\n\n');

    const prompt = buildRAGPrompt(query, context);

    let answer = await withRetry(
      () => generateAnswer(prompt),
      { maxAttempts: 3, delayMs: 1000 }
    );

    if (answer.includes('Information not found in provided documents')) {
      logger.info('RAG returned "not found" - using Gemini LLM fallback');
      
      const fallbackPrompt = `Answer the following question concisely and accurately:\n\nQUESTION: ${query}\n\nANSWER:`;
      answer = await withRetry(
        () => generateAnswer(fallbackPrompt),
        { maxAttempts: 3, delayMs: 1000 }
      );

      return res.status(200).json({
        answer,
        sources: [{
          source: 'Generated by Gemini (answer not found in document chunks)',
        }],
      });
    }

    const sources = matches.map((match) => ({
      source: `Found in documents: ${match.metadata.source}`,
      score: match.score,
      chunkIndex: match.metadata.chunkIndex,
    }));

    logger.info('Query processed successfully with RAG');

    return res.status(200).json({
      answer,
      sources,
    });
  } catch (error) {
    logger.error('Error processing chat request', error);
    return res.status(500).json({
      error: 'Internal server error',
      message: error instanceof Error ? error.message : 'Unknown error',
    });
  }
}
